project:
  type: website
  output-dir: docs

website:
  title: "Rohan Jaspal"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - Hobbies.qmd

format:
  html:
    theme:
      - vapor




